version: "3"

services:  
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    volumes:
      - ./Data_MySQL:/var/lib/mysql
    env_file:
      - ./php.env
    environment:
      - MYSQL_DATABASE="${db_servername}"
      - MYSQL_USER="${db_username}"
      - MYSQL_PASSWORD="${db_password}"
      - MYSQL_ROOT_PASSWORD="${db_password}"
    command:
      - "--character-set-server=utf8"
    ports:
      - "3306:3306" 
    networks:
      sample:
        ipv4_address: 172.99.0.10
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    depends_on:
      - mysql
    networks:
      sample:
        ipv4_address: 172.99.0.11
    volumes:
      - ./Data_Redis:/data
  php:
    container_name: php
    build:
      context: ./
      dockerfile: php.dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - ./APP:/code 
    env_file:
      - ./php.env
    networks:
      - sample
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - mysql
      - redis
      - php
    ports:
      - "8080:80"
    volumes:
        - ./APP/Sample:/code/sample
        - ./site-sample.conf:/etc/nginx/conf.d/default.conf
        - ./Log/Sample/error.log:/var/log/nginx/error.log
        - ./Log/Sample/access.log:/var/log/nginx/access.log 
    networks:
      sample:
        ipv4_address: 172.99.0.20

networks:
  sample:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.99.0.0/16 